### ISSUE TITLE
tbprofiler error

### ISSUE THREAD

**Issue by sherrie9** [BCCDC-PHL/tbprofiler-nf#2]
It is not an error of tbprofiler-nf. but some samples can cause tbprofiler to fail, for unclear reasons. 
Could we add ignore errors for those samples so the pipeline can run on the rest of the samples?

**Comment by dfornika** [comment]
(error message was provided by email in a screenshot, but includes sample identifiers and other information that we shouldn't post to GitHub)

It looks like the error is happening here:

https://github.com/jodyphelan/TBProfiler/blob/76c0b5d5579bef8de331401f9ad695f85f6819aa/tbprofiler/reformat.py#L72

...where there’s a list comprehension (statement like: `[x for x in ....]`), then an array access of the first element (`[...][0]`)

```python
[i for i,d in enumerate(rank) if d in csq["type"]][0]
```

...which is throwing an `IndexError` exception because that list comprehension is evaluating to an empty list, so there is no first element.

I’m looking at the latest version of TBprofiler, and it looks like the ‘reformat’ method has been rewritten:

https://github.com/jodyphelan/TBProfiler/blob/9c7ef32aecdc2e5c96e21b8dae4a91e5f1e694af/tbprofiler/reformat.py#L93-L111

...to use the ‘select_csq’ method from ‘pathogen-profiler’:

https://github.com/jodyphelan/pathogen-profiler/blob/f336b16bd5a3186d7532c5c3940d595a69e5dd09/pathogenprofiler/utils.py#L151-L182

...which calls this ‘select_most_relevant_csq’ method:

https://github.com/jodyphelan/pathogen-profiler/blob/f336b16bd5a3186d7532c5c3940d595a69e5dd09/pathogenprofiler/utils.py#L130-L141

...which seems to have been re-written compared to the version used in the TBProfiler that’s currently used in this pipeline.

So I think it would be worth trying to update TBProfiler to see if that fixes the issue.
